spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/kupanga_dev
    username: kupanga
    password: devpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

minio:
  endpoint: http://localhost:9001
  access-key: minioadmin
  secret-key: minioadmin

app:
  url: http://localhost:4200/
  reset-link: http://localhost:4200/auth/reset-password?token=
  url-login: http://localhost:4200/auth/login
  url-mino: http://localhost:9000